Description: Kinesis

Parameters:
  CloudformationStackName:
    Type: String
    Description: The Cloudformation Stack Name

Resources:
  AWSServerlessExampleKinesis:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: !Sub ${CloudformationStackName}-Kinesis
      ShardCount: 1